Repository WordPress/plugin-check, pull requests merged in 2023-11, with the labels that each got.

#315 Implement `Check_Collection` to separate concerns for check filtering from `Check_Repository`
  includes/Checker/Abstract_Check_Runner.php
  includes/Checker/Check_Collection.php
  includes/Checker/Check_Repository.php
  includes/Checker/Default_Check_Collection.php
  includes/Checker/Default_Check_Repository.php
  phpmd.xml
  tests/phpunit/Checker/Check_Categories_Tests.php
  tests/phpunit/Checker/Default_Check_Collection_Tests.php
  tests/phpunit/Checker/Default_Check_Repository_Tests.php
Labels: [Type] Enhancement, Infrastructure, Architecture Review

#318 CLI: Add `--exclude-checks` support
  includes/CLI/Plugin_Check_Command.php
  includes/Checker/AJAX_Runner.php
  includes/Checker/Abstract_Check_Runner.php
  includes/Checker/CLI_Runner.php
  includes/Checker/Check_Categories.php
  includes/Checker/Check_Collection.php
  includes/Checker/Default_Check_Collection.php
  includes/Checker/Default_Check_Repository.php
  tests/phpunit/Checker/Check_Categories_Tests.php
  tests/phpunit/Checker/Default_Check_Collection_Tests.php
Labels: [Type] Enhancement, WP-CLI

#215 Functional tests for WP-CLI commands
  .github/workflows/behat-test.yml
  behat.yml
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/behat/features/plugin-check.feature
  tests/behat/includes/FeatureContext.php
  tests/behat/utils/maybe-generate-wp-cli-coverage.php
Labels: Infrastructure, WP-CLI

#321 Set up code coverage for unit tests
  .github/workflows/php-test.yml
  .gitignore
  build-cs/composer.json
  build-cs/composer.lock
  build-phpunit/composer.json
  codecov.yml
  composer.json
  composer.lock
  includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php
  package-lock.json
  package.json
  patches/@wordpress+env+8.11.0.patch
  phpcs.xml.dist
  phpunit.xml.dist
  tests/phpunit/bootstrap.php
  tests/phpunit/multisite.xml
  tests/phpunit/tests/Admin/Admin_AJAX_Tests.php
  tests/phpunit/tests/Admin/Admin_Page_Tests.php
  tests/phpunit/tests/Checker/AJAX_Runner_Tests.php
  tests/phpunit/tests/Checker/CLI_Runner_Tests.php
  tests/phpunit/tests/Checker/Check_Categories_Tests.php
  tests/phpunit/tests/Checker/Check_Context_Tests.php
  tests/phpunit/tests/Checker/Check_Result_Tests.php
  tests/phpunit/tests/Checker/Checks/Code_Obfuscation_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Enqueued_Scripts_In_Footer_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Enqueued_Scripts_Size_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Enqueued_Styles_Scope_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/File_Type_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/I18n_Usage_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Late_Escaping_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Localhost_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/No_Unfiltered_Uploads_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Performant_WP_Query_Params_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Plugin_Header_Text_Domain_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Plugin_Review_PHPCS_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Plugin_Updater_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Trademarks_Check_Tests.php
  tests/phpunit/tests/Checker/Checks_Tests.php
  tests/phpunit/tests/Checker/Default_Check_Collection_Tests.php
  tests/phpunit/tests/Checker/Default_Check_Repository_Tests.php
  tests/phpunit/tests/Checker/Preparations/Demo_Posts_Creation_Preparation_Tests.php
  tests/phpunit/tests/Checker/Preparations/Force_Single_Plugin_Preparation_Tests.php
  tests/phpunit/tests/Checker/Preparations/Universal_Runtime_Preparation_Tests.php
  tests/phpunit/tests/Checker/Preparations/Use_Minimal_Theme_Preparation_Tests.php
  tests/phpunit/tests/Checker/Runtime_Environment_Setup_Tests.php
  tests/phpunit/tests/Plugin_Context_Tests.php
  tests/phpunit/tests/Plugin_Main_Tests.php
  tests/phpunit/tests/Utilities/Plugin_Request_Utility_Tests.php
  tests/phpunit/utils/Traits/With_Mock_Filesystem.php
Labels: Infrastructure

#276 Create a way to remove certain readme warnings, contributors_ignored.
  checks/readme.php
  readme.txt
Labels: [Type] Bug, Alpha Plugin
