Repository WordPress/plugin-check, pull requests merged in 2024-04, with the labels that each got.

#453 Fix fatal error introduced in #449
  .github/workflows/behat-test.yml
  .github/workflows/php-test.yml
  includes/Plugin_Context.php
  tests/behat/features/plugin-check.feature
  tests/phpstan/stubs/wp-cli.php
Labels: [Type] Bug

#457 Bump PHP requirement to 7.2+
  .github/workflows/behat-test.yml
  .github/workflows/php-test.yml
  build-cs/composer.json
  composer.json
  composer.lock
  phpstan.neon.dist
  plugin.php
  readme.txt
Labels: [Type] Enhancement

#462 Update PHP version in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: [Type] Documentation
