Repository WordPress/plugin-check, pull requests merged in 2024-09, with the labels that each got.

#598 Prevent that runtime checks are allowed in CLI context when they cannot be used
  includes/Checker/Abstract_Check_Runner.php
  includes/Checker/CLI_Runner.php
Labels: [Type] Bug

#594 Updated named functions and tests
  phpcs-rulesets/plugin-review.xml
  tests/phpunit/testdata/plugins/test-plugin-review-phpcs-errors/load.php
  tests/phpunit/tests/Checker/Checks/Plugin_Review_PHPCS_Check_Tests.php
Labels: [Type] Enhancement

#605 Add check for plugin headers
  includes/Checker/Checks/Plugin_Repo/Plugin_Header_Fields_Check.php
  includes/Checker/Checks/Plugin_Repo/Plugin_Header_Text_Domain_Check.php
  includes/Checker/Default_Check_Repository.php
  tests/behat/features/plugin-check-severity.feature
  tests/behat/features/plugin-check.feature
  tests/behat/features/plugin-list-checks.feature
  tests/phpunit/testdata/plugins/test-plugin-header-fields-with-errors/load.php
  tests/phpunit/testdata/plugins/test-plugin-header-text-domain-with-errors/load.php
  tests/phpunit/testdata/plugins/test-plugin-header-text-domain-without-errors/load.php
  tests/phpunit/tests/Checker/Checks/Plugin_Header_Fields_Check_Tests.php
  tests/phpunit/tests/Checker/Checks/Plugin_Header_Text_Domain_Check_Tests.php
Labels: [Type] Enhancement, [Team] Plugin Review

#608 Improve `active_plugins` filter
  includes/Checker/Abstract_Check_Runner.php
  includes/Checker/Preparations/Force_Single_Plugin_Preparation.php
  tests/behat/features/plugin-check.feature
Labels: [Type] Bug

#612 Allow runtime initialization even when only addon checks are requested
  includes/Checker/Abstract_Check_Runner.php
  includes/Checker/Check_Collection.php
  includes/Checker/Default_Check_Collection.php
  includes/Checker/Exception/Invalid_Check_Slug_Exception.php
  tests/behat/features/plugin-check.feature
Labels: [Type] Bug

#625 Add warning for mismatched plugin name
  includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-multiple-parser-warnings/load.php
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-parser-warnings/load.php
  tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php
Labels: [Type] Enhancement, [Team] Plugin Review

#630 Improve check for Requires Plugins header
  includes/Checker/Checks/Plugin_Repo/Plugin_Header_Fields_Check.php
  tests/phpunit/testdata/plugins/test-plugin-unfiltered-uploads-with-errors/load.php
  tests/phpunit/tests/Checker/Checks/Plugin_Header_Fields_Check_Tests.php
Labels: [Type] Bug

#626 Add validation for Contributors in readme
  includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-md-with-errors/readme.md
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-parser-warnings/readme.txt
  tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php
Labels: Checks

#646 Change error type for ValidatedSanitizedInput rule
  phpcs-rulesets/plugin-review.xml
  tests/phpunit/tests/Checker/Checks/Plugin_Review_PHPCS_Check_Tests.php
Labels: [Team] Plugin Review

#647 Rename `test-content` folder to `runtime-content`
  codecov.yml
  includes/Checker/Preparations/Universal_Runtime_Preparation.php
  runtime-content/themes/wp-empty-theme/comments.php
  runtime-content/themes/wp-empty-theme/footer.php
  runtime-content/themes/wp-empty-theme/functions.php
  runtime-content/themes/wp-empty-theme/header.php
  runtime-content/themes/wp-empty-theme/inc/back-compat.php
  runtime-content/themes/wp-empty-theme/inc/template-functions.php
  runtime-content/themes/wp-empty-theme/inc/template-tags.php
  runtime-content/themes/wp-empty-theme/index.php
  runtime-content/themes/wp-empty-theme/min-style.css
  runtime-content/themes/wp-empty-theme/searchform.php
  runtime-content/themes/wp-empty-theme/style.css
  tests/phpunit/tests/Checker/Preparations/Use_Minimal_Theme_Preparation_Tests.php
Labels: Infrastructure

#650 Introduce slug argument in CLI
  docs/CLI.md
  includes/CLI/Plugin_Check_Command.php
  includes/Checker/AJAX_Runner.php
  includes/Checker/Abstract_Check_Runner.php
  includes/Checker/CLI_Runner.php
  includes/Checker/Checks/Plugin_Repo/Plugin_Header_Fields_Check.php
  includes/Plugin_Context.php
  tests/behat/features/plugin-check.feature
  tests/phpunit/tests/Plugin_Context_Tests.php
Labels: Infrastructure, WP-CLI

#566 Add new `Offloading_Files_Check` check
  .distignore
  .github/workflows/deploy.yml
  .github/workflows/php-lint.yml
  .github/workflows/php-test.yml
  composer.json
  composer.lock
  includes/Checker/Checks/Plugin_Repo/Offloading_Files_Check.php
  includes/Checker/Default_Check_Repository.php
  phpcs-sniffs/.gitignore
  phpcs-sniffs/PluginCheck/Sniffs/CodeAnalysis/EnqueuedResourceOffloadingSniff.php
  phpcs-sniffs/PluginCheck/Sniffs/CodeAnalysis/OffloadingSniff.php
  phpcs-sniffs/PluginCheck/Tests/AbstractSniffUnitTest.php
  phpcs-sniffs/PluginCheck/Tests/CodeAnalysis/EnqueuedResourceOffloadingUnitTest.inc
  phpcs-sniffs/PluginCheck/Tests/CodeAnalysis/EnqueuedResourceOffloadingUnitTest.php
  phpcs-sniffs/PluginCheck/Tests/CodeAnalysis/OffloadingUnitTest.inc
  phpcs-sniffs/PluginCheck/Tests/CodeAnalysis/OffloadingUnitTest.php
  phpcs-sniffs/PluginCheck/ruleset.xml
  phpcs-sniffs/Tests/bootstrap.php
  phpcs-sniffs/composer.json
  phpcs-sniffs/composer.lock
  phpcs-sniffs/phpcs.xml.dist
  phpcs-sniffs/phpunit.xml.dist
  phpmd.xml
  readme.txt
  tests/phpunit/testdata/plugins/test-plugin-offloaded-files-check-with-errors/load.php
  tests/phpunit/tests/Checker/Checks/Offloading_Files_Check_Test.php
Labels: [Type] Enhancement

#670 Check restricted plugin header fields
  includes/Checker/Checks/Plugin_Repo/Plugin_Header_Fields_Check.php
  tests/phpunit/testdata/plugins/test-plugin-header-fields-with-errors/load.php
  tests/phpunit/tests/Checker/Checks/Plugin_Header_Fields_Check_Tests.php
Labels: [Type] Enhancement, [Team] Plugin Review

#668 Do not go for next check if Stable Tag value is trunk
  includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php
  tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php
Labels: [Type] Enhancement, [Team] Plugin Review

#674 Convert requires plugin header to error
  includes/Checker/Checks/Plugin_Repo/Plugin_Header_Fields_Check.php
  tests/phpunit/tests/Checker/Checks/Plugin_Header_Fields_Check_Tests.php
Labels: [Type] Enhancement, [Team] Plugin Review

#681 Allow `runtime-set` in Abstract_PHP_CodeSniffer_Check class and implement it in I18n_Usage_Check
  includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php
  includes/Checker/Checks/General/I18n_Usage_Check.php
  includes/Checker/Checks/Performance/Enqueued_Resources_Check.php
  includes/Checker/Checks/Performance/Enqueued_Scripts_In_Footer_Check.php
  includes/Checker/Checks/Performance/Performant_WP_Query_Params_Check.php
  includes/Checker/Checks/Plugin_Repo/Offloading_Files_Check.php
  includes/Checker/Checks/Plugin_Repo/Plugin_Review_PHPCS_Check.php
  includes/Checker/Checks/Security/Direct_DB_Queries_Check.php
  includes/Checker/Checks/Security/Late_Escaping_Check.php
  tests/phpunit/testdata/plugins/test-plugin-i18n-usage-without-errors/load.php
  tests/phpunit/testdata/plugins/test-plugin-ignore-directories/custom_directory/error.php
  tests/phpunit/testdata/plugins/test-plugin-ignore-directories/load.php
  tests/phpunit/testdata/plugins/test-plugin-ignore-files/bar.php
  tests/phpunit/testdata/plugins/test-plugin-ignore-files/foobar.php
  tests/phpunit/testdata/plugins/test-plugin-ignore-files/subdirectory/error.php
  tests/phpunit/tests/Checker/Checks/I18n_Usage_Check_Tests.php
Labels: [Type] Enhancement, Infrastructure

#678 Added Missing Global Documentation
  includes/Checker/Runtime_Environment_Setup.php
Labels: [Type] Documentation
