Repository WordPress/plugin-check, pull requests merged in 2024-08, with the labels that each got.

#557 Support passing a URL for individual check results
  assets/js/plugin-check-admin.js
  includes/CLI/Plugin_Check_Command.php
  includes/Checker/Check_Result.php
  includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php
  includes/Traits/Amend_Check_Result.php
  templates/results-row.php
  tests/behat/features/plugin-check.feature
  tests/phpunit/tests/Checker/Check_Result_Tests.php
Labels: [Type] Enhancement

#542 CLI: Support checking a plugin from a URL
  composer.json
  composer.lock
  includes/Checker/Abstract_Check_Runner.php
  includes/Utilities/Plugin_Request_Utility.php
  tests/behat/features/plugin-check-remote.feature
Labels: [Type] Enhancement

#560 Strip tags in CLI output
  includes/CLI/Plugin_Check_Command.php
  includes/Traits/Amend_Check_Result.php
Labels: [Type] Enhancement

#532 Update code obfuscation check to show errors with line and column
  includes/Checker/Checks/Abstract_File_Check.php
  includes/Checker/Checks/Plugin_Repo/Code_Obfuscation_Check.php
  tests/phpunit/testdata/plugins/test-plugin-code-obfuscation-ioncube-errors/load.php
  tests/phpunit/tests/Checker/Checks/Code_Obfuscation_Check_Tests.php
Labels: [Type] Enhancement, [Team] Plugin Review

#576 Fix typo in `props-bot.yml` file
  .github/workflows/props-bot.yml
Labels: Infrastructure

#581 Update feature tests for remote zip check
  tests/behat/features/plugin-check-remote.feature
Labels: Infrastructure

#583 Enable `ValidatedSanitizedInput` rule in plugin review check
  phpcs-rulesets/plugin-review.xml
  tests/phpunit/testdata/plugins/test-plugin-review-phpcs-errors/load.php
  tests/phpunit/testdata/plugins/test-plugin-review-phpcs-without-errors/load.php
  tests/phpunit/tests/Checker/Checks/Plugin_Review_PHPCS_Check_Tests.php
Labels: Checks
