Repository WordPress/plugin-check, pull requests merged in 2024-07, with the labels that each got.

#485 Implement `Enqueued_Scripts_Scope_Check`
  includes/Checker/Checks/Enqueued_Scripts_Scope_Check.php
  tests/phpunit/testdata/plugins/test-plugin-enqueued-scripts-scope-check-with-error/home.js
  tests/phpunit/testdata/plugins/test-plugin-enqueued-scripts-scope-check-with-error/load.php
  tests/phpunit/testdata/plugins/test-plugin-enqueued-scripts-scope-check-with-error/script.js
  tests/phpunit/testdata/plugins/test-plugin-enqueued-scripts-scope-check-without-error/load.php
  tests/phpunit/testdata/plugins/test-plugin-enqueued-scripts-scope-check-without-error/script.js
  tests/phpunit/tests/Checker/Checks/Enqueued_Scripts_Scope_Check_Tests.php
Labels: [Type] Enhancement, Checks, [Team] Performance

#483 Readme Check: Compare `Tested up to` value with latest stable version
  includes/Checker/Checks/Plugin_Readme_Check.php
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-md-without-errors/readme.md
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-without-errors/readme.txt
  tests/phpunit/testdata/plugins/test-plugin-root-readme-without-errors/readme.txt
  tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php
Labels: [Type] Enhancement

#331 Add Enqueued Resources check
  includes/Checker/Checks/Enqueued_Resources_Check.php
  includes/Checker/Default_Check_Repository.php
  tests/phpunit/testdata/plugins/test-plugin-enqueued-resources-with-errors/load.php
  tests/phpunit/testdata/plugins/test-plugin-enqueued-resources-without-errors/load.php
  tests/phpunit/tests/Checker/Checks/Enqueued_Resources_Check_Tests.php
Labels: [Team] Performance, [Team] Plugin Review

#511 Update patch for `@wordpress/env`
  patches/@wordpress+env+10.2.0.patch
Labels: Infrastructure

#512 PHPUnit: Do not pass `--verbose` arg
  composer.json
  package.json
Labels: Infrastructure

#496 Trademarks check fails should show as a warning
  includes/Checker/Checks/Trademarks_Check.php
  tests/phpunit/tests/Checker/Checks/Trademarks_Check_Tests.php
Labels: [Team] Plugin Review

#399 Detect localhost/127.0.0.1 code in multiple files
  includes/Checker/Checks/Abstract_File_Check.php
  includes/Checker/Checks/Localhost_Check.php
  tests/phpunit/testdata/plugins/test-plugin-localhost-with-errors/another.php
  tests/phpunit/tests/Checker/Checks/Localhost_Check_Tests.php
Labels: [Team] Plugin Review

#521 Conditional display of edit links
  includes/Plugin_Context.php
  includes/Traits/File_Editor_URL.php
Labels: [Type] Enhancement, WP Admin

#525 Strengthen readme finder to exclude invalid readme files
  includes/Traits/Find_Readme.php
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-errors-invalid-readme/.readme.txt
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-errors-invalid-readme/foo-readme.txt
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-errors-invalid-readme/load.php
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-errors-invalid-readme/readme.txt.md
  tests/phpunit/testdata/plugins/test-plugin-plugin-readme-errors-invalid-readme/test.readme.txt
  tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php
Labels: [Type] Enhancement, Checks

#531 Update @wordpress/env
  package-lock.json
  package.json
  patches/@wordpress+env+10.3.0.patch
Labels: dependencies, javascript

#519 Add `Non_Blocking_Scripts_Check`
  includes/Checker/Checks/Performance/Non_Blocking_Scripts_Check.php
  includes/Checker/Default_Check_Repository.php
  tests/phpunit/testdata/plugins/test-plugin-non-blocking-scripts-check/load.php
  tests/phpunit/tests/Checker/Checks/Non_Blocking_Scripts_Check_Tests.php
Labels: [Type] Enhancement, Checks, [Team] Performance

#461 Add some initial minimal docs for each check
  docs/creating-a-runtime-check.md
  includes/Admin/Admin_Page.php
  includes/CLI/Plugin_Check_Command.php
  includes/Checker/Check.php
  includes/Checker/Checks/General/I18n_Usage_Check.php
  includes/Checker/Checks/Performance/Enqueued_Resources_Check.php
  includes/Checker/Checks/Performance/Enqueued_Scripts_In_Footer_Check.php
  includes/Checker/Checks/Performance/Enqueued_Scripts_Scope_Check.php
  includes/Checker/Checks/Performance/Enqueued_Scripts_Size_Check.php
  includes/Checker/Checks/Performance/Enqueued_Styles_Scope_Check.php
  includes/Checker/Checks/Performance/Enqueued_Styles_Size_Check.php
  includes/Checker/Checks/Performance/Non_Blocking_Scripts_Check.php
  includes/Checker/Checks/Performance/Performant_WP_Query_Params_Check.php
  includes/Checker/Checks/Plugin_Repo/Code_Obfuscation_Check.php
  includes/Checker/Checks/Plugin_Repo/File_Type_Check.php
  includes/Checker/Checks/Plugin_Repo/Localhost_Check.php
  includes/Checker/Checks/Plugin_Repo/No_Unfiltered_Uploads_Check.php
  includes/Checker/Checks/Plugin_Repo/Plugin_Header_Text_Domain_Check.php
  includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php
  includes/Checker/Checks/Plugin_Repo/Plugin_Review_PHPCS_Check.php
  includes/Checker/Checks/Plugin_Repo/Plugin_Updater_Check.php
  includes/Checker/Checks/Plugin_Repo/Trademarks_Check.php
  includes/Checker/Checks/Security/Direct_DB_Queries_Check.php
  includes/Checker/Checks/Security/Late_Escaping_Check.php
  tests/phpunit/testdata/Checks/Category_Check_Five.php
  tests/phpunit/testdata/Checks/Category_Check_Four.php
  tests/phpunit/testdata/Checks/Category_Check_One.php
  tests/phpunit/testdata/Checks/Category_Check_Seven.php
  tests/phpunit/testdata/Checks/Category_Check_Six.php
  tests/phpunit/testdata/Checks/Category_Check_Three.php
  tests/phpunit/testdata/Checks/Category_Check_Two.php
  tests/phpunit/testdata/Checks/Check_Without_Category.php
  tests/phpunit/testdata/Checks/Empty_Check.php
  tests/phpunit/testdata/Checks/Error_Check.php
  tests/phpunit/testdata/Checks/Experimental_Runtime_Check.php
  tests/phpunit/testdata/Checks/Experimental_Static_Check.php
  tests/phpunit/testdata/Checks/Invalid_Check.php
  tests/phpunit/testdata/Checks/Runtime_Check.php
  tests/phpunit/testdata/Checks/Static_Check.php
Labels: [Type] Documentation
