Repository WordPress/plugin-check, pull requests merged in 2024-06, with the labels that each got.

#474 Upgrade `@wordpress/env` to ^10.1.0
  package-lock.json
  package.json
Labels: dependencies

#473 Fix relative wp-env paths when host filepaths contain spaces
  package.json
Labels: Infrastructure

#414 Detect missing readme headers
  includes/Checker/Checks/Plugin_Readme_Check.php
  tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php
Labels: [Team] Plugin Review
