Repository WordPress/plugin-check, pull requests merged in 2025-02, with the labels that each got.

#867 Improve license check for Apache
  includes/Traits/License_Utils.php
  tests/phpunit/tests/Traits/License_Utils_Tests.php
Labels: [Type] Enhancement, [Team] Plugin Review

#872 Add Behat test for experimental checks from addon
  tests/behat/features/plugin-check.feature
  tests/behat/testdata/pcp-addon/Example_Experimental_Check.php
  tests/behat/testdata/pcp-addon/pcp-addon.php
Labels: Testing

#878 Make sure headers are not empty in the requires header check
  includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php
Labels: [Type] Bug, [Team] Plugin Review

#874 Add include experimental option in admin
  assets/js/plugin-check-admin.js
  includes/Admin/Admin_AJAX.php
  includes/Admin/Admin_Page.php
  includes/Checker/AJAX_Runner.php
  templates/admin-page.php
Labels: [Type] Enhancement

#865 Fix incorrect database tables being referenced on subsites in Multisite
  includes/Checker/Preparations/Use_Custom_DB_Tables_Preparation.php
  includes/Checker/Runtime_Environment_Setup.php
  includes/Traits/Amend_DB_Base_Prefix.php
  tests/phpunit/tests/Traits/Amend_DB_Base_Prefix_Tests.php
Labels: [Type] Bug
